# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p_mol2Inchi <- function(xp) {
    .Call('RRDKit_p_mol2Inchi', PACKAGE = 'RRDKit', xp)
}

p_Inchi2InchiKey <- function(x) {
    .Call('RRDKit_p_Inchi2InchiKey', PACKAGE = 'RRDKit', x)
}

#' Map Inchi to molecule
#'
#' @param x a  molecule
#' @param sanitize bool
#' @param removeHs bool
#' @return a molecule
Inchi2Mol <- function(x, sanitize = FALSE, removeHs = FALSE) {
    .Call('RRDKit_Inchi2Mol', PACKAGE = 'RRDKit', x, sanitize, removeHs)
}

p_smile2mol <- function(smi, sanitize = TRUE) {
    .Call('RRDKit_p_smile2mol', PACKAGE = 'RRDKit', smi, sanitize)
}

p_smarts2mol <- function(smarts) {
    .Call('RRDKit_p_smarts2mol', PACKAGE = 'RRDKit', smarts)
}

p_molIsNil <- function(xp) {
    .Call('RRDKit_p_molIsNil', PACKAGE = 'RRDKit', xp)
}

p_mol2smiles <- function(xp) {
    .Call('RRDKit_p_mol2smiles', PACKAGE = 'RRDKit', xp)
}

p_mol2svg <- function(xp) {
    .Call('RRDKit_p_mol2svg', PACKAGE = 'RRDKit', xp)
}

#' map a molecule to a maccs fingerprints
#'
#' @param xp a molecule
#' @return a vector
mol2maccs <- function(xp) {
    .Call('RRDKit_mol2maccs', PACKAGE = 'RRDKit', xp)
}

#' map a molecule to a morgan fingerprints (atom environement)
#'
#' @param xp a molecule
#' @param radius radius of scaffold
#' @param nBits final length
#' @param useFeatures useFeatures
#' @return a vector
mol2morgan <- function(xp, radius = 2L, nBits = 2048L, useFeatures = FALSE) {
    .Call('RRDKit_mol2morgan', PACKAGE = 'RRDKit', xp, radius, nBits, useFeatures)
}

p_writeSdf <- function(file, pv, setForceV3000 = FALSE) {
    invisible(.Call('RRDKit_p_writeSdf', PACKAGE = 'RRDKit', file, pv, setForceV3000))
}

p_molSupplier <- function(file, sanitize = TRUE, removeHs = TRUE, strictParsing = TRUE) {
    .Call('RRDKit_p_molSupplier', PACKAGE = 'RRDKit', file, sanitize, removeHs, strictParsing)
}

p_molSupplier_atEnd <- function(xp) {
    .Call('RRDKit_p_molSupplier_atEnd', PACKAGE = 'RRDKit', xp)
}

p_molSupplier_next <- function(xp) {
    .Call('RRDKit_p_molSupplier_next', PACKAGE = 'RRDKit', xp)
}

p_molSupplier_reset <- function(xp) {
    invisible(.Call('RRDKit_p_molSupplier_reset', PACKAGE = 'RRDKit', xp))
}

p_molGetPropList <- function(xp) {
    .Call('RRDKit_p_molGetPropList', PACKAGE = 'RRDKit', xp)
}

p_molGetProp <- function(xp, property) {
    .Call('RRDKit_p_molGetProp', PACKAGE = 'RRDKit', xp, property)
}

p_molSetProp <- function(xp, property, key) {
    invisible(.Call('RRDKit_p_molSetProp', PACKAGE = 'RRDKit', xp, property, key))
}

#' split molecule to brics fragment
#'
#' @param xp a molecule
#' @return a BRICS fragment
fragmentOnBRICSBonds <- function(xp) {
    .Call('RRDKit_fragmentOnBRICSBonds', PACKAGE = 'RRDKit', xp)
}

#' SubstructMatch
#'
#' @param xp_mol a molecule
#' @param xp_query a template molecule (from a smart)
#' @return bool
SubstructMatch <- function(xp_mol, xp_query) {
    .Call('RRDKit_SubstructMatch', PACKAGE = 'RRDKit', xp_mol, xp_query)
}

p_mol2mw <- function(xp) {
    .Call('RRDKit_p_mol2mw', PACKAGE = 'RRDKit', xp)
}

p_mol2TPSA <- function(xp) {
    .Call('RRDKit_p_mol2TPSA', PACKAGE = 'RRDKit', xp)
}

p_mol2LogP <- function(xp) {
    .Call('RRDKit_p_mol2LogP', PACKAGE = 'RRDKit', xp)
}

p_mol2murcko <- function(xp) {
    .Call('RRDKit_p_mol2murcko', PACKAGE = 'RRDKit', xp)
}

p_computeGasteigerCharges <- function(xp) {
    .Call('RRDKit_p_computeGasteigerCharges', PACKAGE = 'RRDKit', xp)
}

p_kekulize <- function(xp, markAtomsBonds = TRUE, maxBackTracks = 100L) {
    invisible(.Call('RRDKit_p_kekulize', PACKAGE = 'RRDKit', xp, markAtomsBonds, maxBackTracks))
}

p_molCompute2DCoords <- function(xp) {
    invisible(.Call('RRDKit_p_molCompute2DCoords', PACKAGE = 'RRDKit', xp))
}

