# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smiles2mol <- function(smi) {
    .Call('RRDKit_smiles2mol', PACKAGE = 'RRDKit', smi)
}

smarts2mol <- function(smi) {
    .Call('RRDKit_smarts2mol', PACKAGE = 'RRDKit', smi)
}

p_molIsNil <- function(xp) {
    .Call('RRDKit_p_molIsNil', PACKAGE = 'RRDKit', xp)
}

mol2smiles <- function(xp) {
    .Call('RRDKit_mol2smiles', PACKAGE = 'RRDKit', xp)
}

mol2svg <- function(xp) {
    .Call('RRDKit_mol2svg', PACKAGE = 'RRDKit', xp)
}

mol2maccs <- function(xp) {
    .Call('RRDKit_mol2maccs', PACKAGE = 'RRDKit', xp)
}

mol2topologicalFingerprints <- function(xp) {
    .Call('RRDKit_mol2topologicalFingerprints', PACKAGE = 'RRDKit', xp)
}

mol2morgan <- function(xp, radius = 2L, nBits = 2048L, useFeatures = FALSE) {
    .Call('RRDKit_mol2morgan', PACKAGE = 'RRDKit', xp, radius, nBits, useFeatures)
}

molSupplierWrite <- function(file, xp) {
    invisible(.Call('RRDKit_molSupplierWrite', PACKAGE = 'RRDKit', file, xp))
}

p_writeSdf <- function(file, pv) {
    invisible(.Call('RRDKit_p_writeSdf', PACKAGE = 'RRDKit', file, pv))
}

molSupplier <- function(file) {
    .Call('RRDKit_molSupplier', PACKAGE = 'RRDKit', file)
}

molSupplier_atEnd <- function(xp) {
    .Call('RRDKit_molSupplier_atEnd', PACKAGE = 'RRDKit', xp)
}

molSupplier_next <- function(xp) {
    .Call('RRDKit_molSupplier_next', PACKAGE = 'RRDKit', xp)
}

molSupplier_reset <- function(xp) {
    invisible(.Call('RRDKit_molSupplier_reset', PACKAGE = 'RRDKit', xp))
}

p_molGetPropList <- function(xp) {
    .Call('RRDKit_p_molGetPropList', PACKAGE = 'RRDKit', xp)
}

p_molGetProp <- function(xp, property) {
    .Call('RRDKit_p_molGetProp', PACKAGE = 'RRDKit', xp, property)
}

p_molSetProp <- function(xp, property, key) {
    invisible(.Call('RRDKit_p_molSetProp', PACKAGE = 'RRDKit', xp, property, key))
}

fragmentOnBRICSBonds <- function(xp) {
    .Call('RRDKit_fragmentOnBRICSBonds', PACKAGE = 'RRDKit', xp)
}

SubstructMatch <- function(xp_mol, xp_query) {
    .Call('RRDKit_SubstructMatch', PACKAGE = 'RRDKit', xp_mol, xp_query)
}

mol2mw <- function(xp) {
    .Call('RRDKit_mol2mw', PACKAGE = 'RRDKit', xp)
}

mol2TPSA <- function(xp) {
    .Call('RRDKit_mol2TPSA', PACKAGE = 'RRDKit', xp)
}

mol2LogP <- function(xp) {
    .Call('RRDKit_mol2LogP', PACKAGE = 'RRDKit', xp)
}

mol2murcko <- function(xp) {
    .Call('RRDKit_mol2murcko', PACKAGE = 'RRDKit', xp)
}

computeGasteigerCharges <- function(xp) {
    .Call('RRDKit_computeGasteigerCharges', PACKAGE = 'RRDKit', xp)
}

